#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Aug 27 17:05:37 2017

@author: Conor
"""


import random 
import numpy as np

agents = []


class Agent(object):
    """A single agent in an organization/network


    Attributes:
        uid: unique ID for agent
        network: The original network id taht the agent is nested in 
        asset: The amount of each asset the agent has
        hierarchy: level in organization (low, medium, hogh, etc)
        coal: 1 if in a coalition with another network or agent and 0 o/w
        
       
        Maybe: 
        Maybe: coal: 1 if in a coalition with another network or agent and 0 o/w
        
    """

    
    #For simplest case, give a random endownment an agent starts with here or
    #a zero endowment for all agents:
    n_agents = 3
    #utility = [] #Store progression of utility over rounds 
    coal = 0
    

    def __init__(self, uid, network=None, asset = [], hierarchy = None):
        
        self.uid = uid
        self.network = network
        self.asset = []
        self.hierarchy = hierarchy
        
        self.init_asset = random.gauss(1, 1)
        self.threshold = .15*(self.init_asset)
        asset.append(self.init_asset)
        
    def __repr__(self):
        return self.uid
    
    def expectedReturn(self, rounds):
  
         #Calculate expected asset return for some # rounds ahead
         estimates = [np.random.normal(1.0, 1.0, rounds) for i in range(rounds) ]
         guess = np.mean(estimates)
    
         return guess
     
    def coerce(self, otherAgent):
        
        if(otherAgent.asset[-1] < otherAgent.threshold):
            otherAgent.coal = 1
            self.coal = 1
        
    def joinCoalition(self, otherAgent):
        #Implement inside of a list comprehension to loop through combinations
        #of agents
        
        #Agent simulates average of 5 rounds ahead -- if > current asset,
        #will want to join a coalition to hedge bets 
        
        #If expected to go under, join coalition; if currently below
        #lowest threshold, also join coalition (work through logical if/else
        #contingences)
        
        if(otherAgent.asset[-1] + otherAgent.expectedReturn(5) < otherAgent.threshold ):
            self.coal = 1
            otherAgent.coal = 1
            return True 
            
        if(otherAgent.asset[-1] + otherAgent.expectedReturn(5) < 0):
            self.coal = 1
            otherAgent.coal = 1
            return True 
            
        if(otherAgent.asset[-1] + otherAgent.expectedReturn >= otherAgent.threshold):
            self.coal = 0
            otherAgent.coal = 0
            return False
            
           
        
        #(Insert combinations of if's that say 'if one needs it but not the
        #other, if both need it, if the other one needs it but not the other,
        #etc.')
        
        #(Use this function in an 'if' statement search about for other agents) 
        
        #if self.asset[-1] + self.expectedReturn(5) < 0:
        

            
        
    def die(self, agent):
        #Remove or delete agent from list or dictionary of agents
        #Call this first, then if agent passes this, moves on to 
        #joinCoalition function
        
        #if agent's assets < 0, agent dies
        
        if(agent.assets[-1] < 0):
        
            if self.agent in agents: 
                agents.remove(agent)
            print('Agent died!')
            return True

        

    def step(self):
        
        
        #Could include an 'if <0 then dead' statement for testing here
        
        #Look at all agents. If they are below their own threshold, 
        #put them aside. These agents can be 'coerced' -- whoever gets to them
        #first gets to assign them to a coalition. If two agents are below
        #their threshold value, then the choosing agent picks only one. If 
        #there's only one agent below threshold, then randomly pick which of 
        #the other two agents gets to coerce.
        
        #IF( not in coalition ):
        #Adjust each agent’s wealth / income / assets by += N(1,1) — could also 
        #change to N(1,theta) with theta ~ U(0,1)
        
     if self.coal < 1:
        self.asset.append(self.asset[-1] + np.random.normal(1.0, 1.0))
     if self.coal == 1:
        self.asset.append(self.asset[-1] + np.random.normal(.75, .25))
      
      
      
    #@abstractmethod
    #def agent_type(self):
    #    """"Return a string representing the type of agent this is."""
    #    pass
